spring.application.name=Online-Library-Management-System
spring.datasource.url=jdbc:mysql://localhost:3306/onlinelibrary
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver=com.mysql.cj.jdbc.Driver
spring.jpa.show-auto=true
spring.jpa.hibernate.ddl-auto=update
spring.security.name=luja
spring.security.password=mhrznluj@2
jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1Qgc2lnbmluZw==